### ISSUE TITLE
unable to register and login properly after fresh installation and registration

### ISSUE THREAD

**Issue by mkumarjha** [moeen-basra/laravel-react#1]
When i installed all and tryied to signup it did not show any error message

**Comment by moeen-basra** [comment]
Did you followed all the steps. 
You better attach a screenshot of your console.

**Comment by moeen-basra** [comment]
you still need help or its working now ?

**Comment by mkumarjha** [comment]
I have followed all steps my app is running but when i try to signup api is not responding . I mean it moving moving .... and after few minutes it redirect on home page with 401 error

**Comment by moeen-basra** [comment]
can you please attach screenshot of your console and network tabs.
It would be easy to figure out the problem.

**Comment by mimrank** [comment]
i face same problem

**Comment by moeen-basra** [comment]
make sure you have updated the APP_URL in .env file

**Comment by tangoun** [comment]
I have checked and followed the steps several times. I have verified the APP_URL in .env file, APP_URL=http://localhost:8000. But I still cannot login

**Comment by moeen-basra** [comment]
@tangoun can you please attach the screenshot for console and network tabs.

**Comment by tangoun** [comment]
Thank for respond. Please check the attachment
- Console Firebug in Firefox
![1](https://user-images.githubusercontent.com/7345723/32936281-3d7fd24c-cba6-11e7-98db-96af82c56a91.PNG)

- Console in Chrome
![chrome_1](https://user-images.githubusercontent.com/7345723/32936308-59a9b582-cba6-11e7-8b25-d969127d8d7a.PNG)

- Network in Chrome
![chrome_2](https://user-images.githubusercontent.com/7345723/32936330-72898a64-cba6-11e7-8cb8-07cefb556fb1.PNG)

**Comment by moeen-basra** [comment]
I'm unable to view the response in console. 
add my skype "m.basra@live.com" I will try to help you.

**Comment by tangoun** [comment]
Thank.
I have uploaded this project. 
Please help to check via this url: http://laravelreact.thizmorning.com/
After I register, errors in console
![capture](https://user-images.githubusercontent.com/7345723/32988939-64dee5d4-cd41-11e7-9a9b-cfbc4f50b726.PNG)
![capture1](https://user-images.githubusercontent.com/7345723/32988943-744e1486-cd41-11e7-9b59-59f8365d6539.PNG)

**Comment by moeen-basra** [comment]
Hi @tangoun please make sure you set your APP_URL=http://laravelreact.thizmorning.com
And you have set proper permissions for your storage folder.

`sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache`

**Comment by tangoun** [comment]
Thank you.
It works online. after I updated APP_URL=http://laravelreact.thizmorning.com

but this project does not work in my local with APP_URL=http://localhost:8000
I don't know what the problem between online and local.

**Comment by moeen-basra** [comment]
You need to make sure if your project is working on 8000 port in your local environment.

**Comment by tangoun** [comment]
In local I run command: php artisan serve, it works with 8000 port, as you can see in my capture images above. That's ok. I'll figure it out. thank you for your prompt response.

**Comment by moeen-basra** [comment]
You are welcome.
