### ISSUE TITLE
Npm run dev Fail

### ISSUE THREAD

**Issue by jackleblack-kpt** [moeen-basra/laravel-react#11]
First, thanks for this project :-)

I have an issue, just after install, I run "npm run dev" and a error appear:

```
ERROR in ./resources/assets/js/layout/index.js
Module build failed: SyntaxError: Unexpected token (15:21)
```

I think that is a problem with the compilation (babel ?).

**Comment by moeen-basra** [comment]
Hi @jackleblack-kpt I just tried a fresh clone and everything works, you can try again follow the steps
remove node_modules folder
remove package-lock and yarn-lock files and any
re install npm packages using npm or yarn

and let me know if you still facing problem

**Comment by jackleblack-kpt** [comment]
I tried what you say, unfortunately nothing happen, I reinstalled packages with Yarn. It seem to be a problem linked with babel .

**Comment by moeen-basra** [comment]
I installed a couple of time after that but I'm not facing problem.

can you check your npm and node version

**Comment by jackleblack-kpt** [comment]
`git clone https://github.com/moeen-basra/laravel-react.git` => ".babelrc","".eslintrc.js",".eslintignore" are missing

**Comment by moeen-basra** [comment]
@jackleblack-kpt  these are all preset in the root, you can just go to the root path of the repo on git hub and can see these files are present in the root
and mix.minfest is auto generated file by npm or yarn compile when you run the command run dev or watch poll

**Comment by moeen-basra** [comment]
@jackleblack-kpt you can clone a fresh project and make sure you are using latest version of node and npm
