### ISSUE TITLE
Help Mix manifest does not exist

### ISSUE THREAD

**Issue by c3budiman** [moeen-basra/laravel-react#12]
The Mix manifest does not exist.
![image](https://user-images.githubusercontent.com/1578830/36972033-3fa16a00-20a0-11e8-9cdd-89ce9470ac69.png)

**Comment by moeen-basra** [comment]
I think you have removed mix.minifest.json from public directory you can copy on from source

**Comment by hopewise** [comment]
I have the same issue, `mix.minifest.json` is not at this public directory of this repository, can you please upload it
