### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by havantuan** [moeen-basra/laravel-react#15]
I cant't login. In reponsive none value.

**Comment by havantuan** [comment]
I can't to view the response in console. How to enable view the response in console?

**Comment by jacekk** [comment]
@havantuan Right click on the request in Network tab and:
1. Copy --> Copy request headers
1. Copy --> Copy response headers
1. Paste both in this very issue.

**Comment by thomasdseao** [comment]
Same error, but the request stay in pending strate ...

The request headers : 
Provisional headers are shown
Accept: application/json
Content-Type: application/json;charset=UTF-8
Origin: http://127.0.0.1:8000
Referer: http://127.0.0.1:8000/login
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
X-CSRF-TOKEN: hzSkE8fUrSG1McPfw3tkRYWZvjNzTo5COAsGcXhz
X-Requested-With: XMLHttpRequest
X-XSRF-TOKEN: eyJpdiI6IjhxRlNid2pWSklMdGEyVjBLZTBBQlE9PSIsInZhbHVlIjoiR1wvMTM5Ym85UGY2dDVJSkRWdzFcL0ErK1pWZ1ArYTBKYk02eWtINEo3RFMxR05Yd0NZcDZCbURJMkh0Q1wvMkNKZnpzTGpxWXFra0R5SFE3RXdNTmoxMWc9PSIsIm1hYyI6ImY4MzcxM2FiYzAwNGRkMDFkYWU0N2JlYjBlOTk4NDEyMTgzY2JiYTRiZmJkNTYwMGQzNTUyNDNlNDY1ZDdjMGUifQ==

And no response, the request stay in pending indefinitely
