### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by thomasdseao** [moeen-basra/laravel-react#16]
I cant login in application, in the network tab, the request stay in pending indefinitely...
Have you a similar error ?

**Comment by HynekS** [comment]
Actually, I have the exactly same issue (both the login and the register form doesn't submit, console doesn't show any errors).

**Comment by thomasdseao** [comment]
Hi HynekS,

I ended up solving it by **using a real virtualhost (LEMP OR WAMP) instead of php artisan serve**.

This problem seems to be related with the php internal Webserver.
If you do "php -S 127.0.0.1:8000" in your public folder it wont work too. Seems like those kind of operations are stricted with the default config for php internal webserver.

**Comment by jacekk** [comment]
@thomasdseao https://stackoverflow.com/a/25651196 - I think I've already pasted that within this projects issues. I guess some info in docs might be helpful.

**Comment by moeen-basra** [comment]
@jacekk.is right

You need to create a nginx local domain and upload the nginx.config.js file as follow

```
mix.browserSync({
    proxy: 'http://laravel-react.test' // localhost domain name
  })
```

**Comment by AyadiDhiaEddine** [comment]
How to do that pls ?

**Comment by moeen-basra** [comment]
which OS are you using ?
