### ISSUE TITLE
ENV constants are not accessible

### ISSUE THREAD

**Issue by Asifali121** [moeen-basra/laravel-react#18]
Hi,
I have cloned this project and followed all installation steps. I am able to see the first screen and others too.
But When I tried to login it thrown an error below::
`0: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

I went for debug and found that `ENV('APP_URL')` always returns null. Actually every env constants are returned as null. I am using windows 7 and wamp.

**Comment by moeen-basra** [comment]
this mean the url you are providing is not proper, check your api url.

**Comment by Asifali121** [comment]
I know the api url is not proper. But the issue is, it is not loading from .env file. I went to print each variable defined in env was returned as null. I had to load .env file manually in bootstrap/app.php to make to working.

**Comment by moeen-basra** [comment]
try updating laravel framework.
