### ISSUE TITLE
404: Client error: `POST http://localhost/oauth/token` resulted in a `404 Not Found` 

### ISSUE THREAD

**Issue by geniux300** [moeen-basra/laravel-react#19]
Hello, first I want to thank you for the great project you have shared with the community. It is really useful.

After following all the steps, I get the following error when trying to login with a user already registered (default users or even new users created)

I'm using XAMPP 3.2.2 to run the project

I have spent several weeks trying to solve this problem, but unfortunately I have not made any progress. I have deleted the project several times and reinstalled everything from scratch, but the result is always the same and I do not know what could be the cause.
I have not modified any line of code so I do not understand why it fails
If you could help me solve this problem I would be grateful.

**Comment by geniux300** [comment]
Thanks for your reply. I have correctly installed the passport. I attach screenshots.
Any idea what could be the cause?

![image](https://user-images.githubusercontent.com/41449592/42994688-0594b2d8-8c0f-11e8-9a9e-2fe9bdd55548.png)
![image](https://user-images.githubusercontent.com/41449592/42994706-187dc8da-8c0f-11e8-9007-c7eb065c6ca0.png)

**Comment by moeen-basra** [comment]
@geniux300 make sure you api calls are landing on proper path. Make sure you are able to access your api on browser or http client using the following path

```
<url>/api/v1/articles/published
```

If not then the issue is with your local configuration of xampp.

**Comment by geniux300** [comment]
Thank you for your answere.
I'm able to access to the url:
![image](https://user-images.githubusercontent.com/41449592/43045206-69174518-8db4-11e8-92de-6fc6ae1f1523.png)
Now I'm using WAMPServer 3.1.3 x64 owing to I thought that the problem was related to xampp.
This is my database (users), where as you can see, when I register a new user, the remember_token is always empty.
![image](https://user-images.githubusercontent.com/41449592/43045234-2ffeffb8-8db5-11e8-84a2-6f1d3eda2057.png)
And this is oauth_clients, which are the same that I have in .env file
![image](https://user-images.githubusercontent.com/41449592/43045252-86082074-8db5-11e8-8218-0b2f130a8fcd.png)

I have followed all the steps. The only thing that I have tested is to use this command: composer require laravel/passport (and php artisan passport:install), and this is the error that I have:

![image](https://user-images.githubusercontent.com/41449592/43045275-e8a705ec-8db5-11e8-8857-01ebc1d25ca3.png)

I have installed several version of league/oauth2-server (in different projects) in order to fix the problem, but unsuccessfully.

**Comment by moeen-basra** [comment]
The laravel passport v5 is already there you just need to run
```
composer install && php artisan passport:install
```
Then copy the password client ID and SECRET to your .env file

I think the issue is with your .env file, screenshot above you provided to .env file check key

APP_URL=localhost

where as in your last comment you attached api response coming from url localhost:8000

set your
```
APP_URL=localhost:8000
```

**Comment by geniux300** [comment]
I have changed the APP_URL=localhost:8000 (only works with APP_URL=http://localhost:8000) by which you indicate me and after recompiling the project, the requests for login and registration have stopped working (they do not show any type of error neither on the web nor in the console)

I have started a new project, which I have attached all the steps I have made with screenshots:

1ºcomposer install && composer update
![image](https://user-images.githubusercontent.com/41449592/43082458-67770898-8e94-11e8-9788-16a49154d5b9.png)

2ºphp artisan migrate and php artisan db:seed
![image](https://user-images.githubusercontent.com/41449592/43082623-c648f4da-8e94-11e8-8a09-720c8c1fe9e6.png)
![image](https://user-images.githubusercontent.com/41449592/43082665-dbbd7e94-8e94-11e8-89cb-5036f3d53f49.png)

3º npm install
![image](https://user-images.githubusercontent.com/41449592/43082860-5ac70c1e-8e95-11e8-92b0-c0dc28585e2c.png)

4ºphp artisan passport:install
![image](https://user-images.githubusercontent.com/41449592/43082924-8ac8b39a-8e95-11e8-9261-9c2c0e1886eb.png)
![image](https://user-images.githubusercontent.com/41449592/43082965-a1d13332-8e95-11e8-809c-d2b864ad0936.png)
![image](https://user-images.githubusercontent.com/41449592/43082990-b3246a0a-8e95-11e8-835c-2a8fda074e9a.png)

5º php artisan key:generate
![image](https://user-images.githubusercontent.com/41449592/43083143-192604d0-8e96-11e8-8098-38b978d89d36.png)

6º php artisan serve
![image](https://user-images.githubusercontent.com/41449592/43083178-32042d2e-8e96-11e8-9e6d-6cf0a9a46ab5.png)
![image](https://user-images.githubusercontent.com/41449592/43083225-4f2c3fe0-8e96-11e8-8cf9-f4261385eece.png)

7º I run: npm run dev to fix it and run php artisan serve again
![image](https://user-images.githubusercontent.com/41449592/43083982-084501e6-8e98-11e8-80af-391d9ec4790c.png)


8º Register a new user
![image](https://user-images.githubusercontent.com/41449592/43083385-a43bd5cc-8e96-11e8-8ab9-36e7e57e5123.png)

When I click on sign up, nothing happens because in the .env file I have http: // localhost: 8000 instead of http: // localhost
![image](https://user-images.githubusercontent.com/41449592/43083461-e118f042-8e96-11e8-8704-d73904960882.png)

BUT the new user is created!!!!
![image](https://user-images.githubusercontent.com/41449592/43083601-310dda54-8e97-11e8-8317-71e84c715f70.png)

If I change APP_URL=http://localhost and recompile and try to login with this new user:
![image](https://user-images.githubusercontent.com/41449592/43083827-b0ff17e6-8e97-11e8-9f89-c7ac6deb3aaf.png)
These are all the steps I take. I do not know what the error could be. As a curiosity (in case it's important, when I run npm run watch, I get the following result, where it indicates that the port is 3000 !!

![image](https://user-images.githubusercontent.com/41449592/43083946-ee4ecf24-8e97-11e8-86a8-2e8aeaac2958.png)

**Comment by bruxter** [comment]
I have the same problem. I've been with this for more than a month and I can not login. I get the same error that describes geniux3000

Does nobody know how to solve it? I think that if the author could upload a YouTube video of the entire installation and configuration process, it would solve all the problems we are having.

**Comment by moeen-basra** [comment]
are you using windows with wamp ?

**Comment by moeen-basra** [comment]
I will try this myself on windows and will let you know.

**Comment by moeen-basra** [comment]
I've tried these steps on windows and linux both its working perfectly fine for me. Do let me know if any of you still facing this problem.
