### ISSUE TITLE
Malformed utf-8 characters.

### ISSUE THREAD

**Issue by AyadiDhiaEddine** [moeen-basra/laravel-react#20]
When i go to the home i see no article , when i try to login i cant when i try to register i cant : the error in my console is malformed utf-8 characters, possibly incorrectly encoded . What to do ? What is the problem ?

**Comment by jacekk** [comment]
Can you paste the error? Or its screenshot? It is really hard to help having such a general and blurry description ;)

**Comment by nicolasflorth** [comment]
If you are using Chrome and the error is not showing correctly, use Mozilla Firefox and you might see where is the problem. At least you will have something visible that can be copy/pasted here. I was in the same situation a few times.
