### ISSUE TITLE
where checkAuth() is used?

### ISSUE THREAD

**Issue by nicolasflorth** [moeen-basra/laravel-react#21]
Hi Moeen,

In js/modules/auth/store/reducer.js is a function checkAuth. Tell me please where this is used?
I can't find it anywhere.
I see is at the top at the file as return checkAuth(state); but where on the service.js it should be used?
Thanks!

**Comment by jacekk** [comment]
It is used in the same very file: https://github.com/moeen-basra/laravel-react/blob/master/resources/assets/js/modules/auth/store/reduer.js#L20

**Comment by jacekk** [comment]
Is is used in here: https://github.com/moeen-basra/laravel-react/blob/master/resources/assets/js/app.js#L22
