### ISSUE TITLE
Authorization: Bearer eyJ0eXAiOiJKV1QiLC...not the same as the access_token inserted in database

### ISSUE THREAD

**Issue by nicolasflorth** [moeen-basra/laravel-react#22]
Can you explain please, why Authorization: Bearer eyJ0eXAiOiJKV1QiLC is not the same as access token inserted into database? 
Database value is 28fbf5feb43f5ddb2c559d26213304612366a2680f5e47be8e544430a4eb9a133c88a03a24f8189a

**Comment by moeen-basra** [comment]
you can check this article for basic understanding, how jwt actually get created.

https://medium.com/vandium-software/5-easy-steps-to-understanding-json-web-tokens-jwt-1164c0adfcec
