### ISSUE TITLE
What is '!!' doing?

### ISSUE THREAD

**Issue by fmake7** [moeen-basra/laravel-react#23]
Hi. moeen.

I am looking at your code.
And, I am studying very much.

Please tell me about function checkAuth.

`isAuthenticated: !! localStorage.getItem ('access_token')`

What is this '!!' doing?

Thank you.

**Comment by moeen-basra** [comment]
!! is Coerces Object to boolean.

https://stackoverflow.com/questions/784929/what-is-the-not-not-operator-in-javascript
