### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by manaxi** [moeen-basra/laravel-react#27]
After npm install I`m getting this message
Binary is fine

> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN img-loader@3.0.1 requires a peer of imagemin@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN laravel-react@2.2.2 No repository field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> added 1536 packages from 949 contributors and audited 19149 packages in 35.414s
> found 1 high severity vulnerability
>   run `npm audit fix` to fix them, or `npm audit` for details

and when i run npm audit

         

>                         Manual Review
>              Some vulnerabilities require your attention to resolve
> 
>           Visit https://go.npm.me/audit-guide for additional guidance
> 
> 
>   High            Missing Origin Validation
> 
>   Package         webpack-dev-server
> 
>   Patched in      >=3.1.6
> 
>   Dependency of   laravel-mix [dev]
> 
>   Path            laravel-mix > webpack-dev-server
> 
>   More info       https://nodesecurity.io/advisories/725
> 
> found 1 high severity vulnerability in 19149 scanned packages
>   1 vulnerability requires manual review. See the full report for details.

npm audit fix doesnt help same problem

**Comment by manaxi** [comment]
> remove your node_modules folder, remove package-lock.json, git pull and try again.
> 
> Its been a while I never used npm and forget to remove package-lock.json file

I have tried to do this thousand times same..

**Comment by moeen-basra** [comment]
app/Http/Controllers/Api/Auth/LoginController.php

line: 37 try dd ($e)
