### ISSUE TITLE
Register fails.

### ISSUE THREAD

**Issue by zayaslui** [moeen-basra/laravel-react#34]
Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by moeen-basra** [comment]
how to recreate this issue ?

**Comment by C4pt4inM** [comment]
Register fails with "401 (Unauthorized)"
steps to recreated: I followed all your steps, homepage runs fine. but login register throws these errors

**Comment by moeen-basra** [comment]
I just upgraded the laravel and react. 
please pull the latest code and try make sure you update the app url in .env file

**Comment by mo-hit** [comment]
I get kind of the same thing, login and register are both stuck in a pending state when looking at the dev tools network tab

**Comment by moeen-basra** [comment]
@mo-hit please upgrade the application, and make sure you have the APP url updated in .env file
