### ISSUE TITLE
404 error API

### ISSUE THREAD

**Issue by b0nb0n** [moeen-basra/laravel-react#35]
Hi,

I try to test the project. I've updated the .env with my values but when I want to register, I've a 404 error on API (log)

POST http://xxxxxx/api/v1/auth/login 404 (Not Found)

This is my .env:

`APP_ENV=production
APP_KEY=base64:xxxxx=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://xxxx.io

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=xx
DB_USERNAME=xx
DB_PASSWORD=xxxx

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=

PERSONAL_CLIENT_ID=1
PERSONAL_CLIENT_SECRET=xxxxxxxxx
PASSWORD_CLIENT_ID=2
PASSWORD_CLIENT_SECRET=xxxxxxxx
`

**Comment by b0nb0n** [comment]
Do you have an idea ?

**Comment by moeen-basra** [comment]
your APP_URL and api url for the frontend should be the same

**Comment by b0nb0n** [comment]
Sorry, I'm not sure to understand. Where can I set the API URL ?

**Comment by b0nb0n** [comment]
I've any route who works, for examples theses 2 routes send 404:

http://xxxxx.io/img/moeen.jpg
http://xxxxx.io/api/v1/auth/login

**Comment by b0nb0n** [comment]
The img is not a good example because this doesn't exist ...lol

But the problem persist for all api call

**Comment by moeen-basra** [comment]
.env
APP_URL=http://xxxx.io

make sure you app sending request to above mentioned APP_URL
