### ISSUE TITLE
Production compile error

### ISSUE THREAD

**Issue by bastolaxantos** [moeen-basra/laravel-react#37]
I am getting this error on compiling for production

CssSyntaxError: E:\css\app.css:13156:19: Missed semicolon

anyone know how to solve this?

**Comment by moeen-basra** [comment]
is this still happening ?

**Comment by moeen-basra** [comment]
I'm sure this issue is been resolved in the new updates, so closing this Issue.
If you still facing any problem please open a new one.

Thanks
