### ISSUE TITLE
browser cache

### ISSUE THREAD

**Issue by Andrew-Kang-G** [moeen-basra/laravel-react#39]
The library 'react-loadable' seems to create js files  consisting of only numbers and they are stored in the 'public' directory. 
In Chrome browser, I have to press 'shift  + F5' instead of 'F5' whenever modifying codes and rebuilding them. This is really an issue in a real server.

**Comment by moeen-basra** [comment]
Thanks @Andrew-Kang-G, I'm little busy with a couple of projects and unable to spare some time for this to review. So either you can create a PR or wait for a while

**Comment by jacekk** [comment]
@Andrew-Kang-G Just open Chrome DevTools, the Network tab and mark the `disable cache` option:

![image](https://user-images.githubusercontent.com/1695878/64077821-31ac0180-ccd4-11e9-80e3-e679b92b0de8.png)

----

> There are only two hard problems in Computer Science:
    cache invalidation and naming things.
    -- Phil Karlton

:smiley:
