### ISSUE TITLE
Register fails. 0: cURL error 7: Failed to connect to localhost port 80:

### ISSUE THREAD

**Issue by DuudeXX8** [moeen-basra/laravel-react#40]
I found  [**this**](https://github.com/moeen-basra/laravel-react/issues/34) question with same error like in my case but you just close this issue without solving the problem so I open new one.

When I register page redirect's me to the Home page and set the `token` in localstorage `null`.

I'll get this error in console 
`
http://localhost:8000/api/v1/auth/login 401 (Unauthorized)`

After if I change page again I redirecting to the login page.And then if I sign in I get this error bottom of the input. 
`0: cURL error 7: Failed to connect to localhost port 80: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

my `APP_URL`

`APP_URL=http://localhost:8000`

**Comment by moeen-basra** [comment]
pull latest code and let me know if it works for you

**Comment by DuudeXX8** [comment]
@moeen-basra  Right now it's not even register or login I click the login or register button the request is going to server but without any respond from server. =(

**Comment by moeen-basra** [comment]
I updated the readme and also added the docker you can try either way.

**Comment by DuudeXX8** [comment]
@moeen-basra  Yup that's working thank's a lot.
