### ISSUE TITLE
sh: cron:refresh-database: not found

### ISSUE THREAD

**Issue by elshobokshy** [moeen-basra/laravel-react#42]
When I try to execute the command `cron:refresh-database` I get the following error : `sh: cron:refresh-database: not found`

Any idea why?

**Comment by jacekk** [comment]
@elshobokshy Just guessing but it looks like an artisan command. Try running `artisan cron:refresh-database`.

**Comment by elshobokshy** [comment]
@jacekk thank you, sir!
