### ISSUE TITLE
Changes not taken into consideration

### ISSUE THREAD

**Issue by elshobokshy** [moeen-basra/laravel-react#43]
Excuse my limited knowledge, I'm new to react. Why is it when I make changes they don't appear ? Even if I try re-entering the npm install && npm run dev command ?

**Comment by jacekk** [comment]
@elshobokshy Try https://github.com/moeen-basra/laravel-react/issues/39 or running `npm run hot`.

P.S.
https://www.udemy.com/courses/search/?src=ukw&q=reactjs&p=1&lang=en&price=price-free :)

**Comment by elshobokshy** [comment]
@jacekk I tried following a react course, but this project doesn't follow any of the guidelins in the tutorials :( Also `npm run hot` is not working, and I'm using VSCode. Thank you for your help!

**Comment by jacekk** [comment]
@elshobokshy `... but this project doesn't follow any of the guidelins in the tutorials ...` - maybe because this is a Laravel application which uses React as the frontend part. Such tutorials might be useful: https://dev.to/lvtdeveloper/using-react-in-a-laravel-application-8fp

I've just checked npm scripts defined in `package.json` and `npm run watch` does the job. While `hot` does not; dunno why, though.

**Comment by elshobokshy** [comment]
@jacekk perfect, thank you ! `npm run watch` is still weirdly not making my changes live and I still have to run the npm commands. 

Also do you have any idea how to prevent the navbar to be shown on every page, and to make it show on only the pages we want ? I can't find where is the code that is defining it in every page.

**Comment by jacekk** [comment]
@elshobokshy `npm run watch` is working, but please bear in mind the 'Disable cache' option in DevTools. It should be `checked` and DevTools has to be open all the time.

Re navbar & footer:
those are displayed in https://github.com/moeen-basra/laravel-react/blob/master/resources/js/layout/Public.js#L21 , but if you had problems finding that yourself, please, check out some React course. Question totally unrelevant to this very project.

**Comment by elshobokshy** [comment]
@jacekk I did find where they were, just no idea how to not show them in a particular page. Thanks for the information tho!

**Comment by jacekk** [comment]
@elshobokshy `react-router` is used, so this should work --> https://reacttraining.com/react-router/web/api/withRouter .

**Comment by elshobokshy** [comment]
@jacekk works like a charm, thank you!

**Comment by moeen-basra** [comment]
@jacekk thanks for quick replies to the community. I really appreciate.
