### ISSUE TITLE
API (Unauthorized)

### ISSUE THREAD

**Issue by elshobokshy** [moeen-basra/laravel-react#44]
Any idea why is the API giving me an `error: "Unauthenticated."` every time I try to login and go to the articles admin page even tho I have the admin value in the database at 1 ?

**Comment by elshobokshy** [comment]
Also everytime I click on the remember me button I get this error : 

```
ree-validate.esm.js?a5bf:315 Uncaught Error: [ree-validate] Validating a non-existent field: "remember". Use "attach()" first.
```

**Comment by jacekk** [comment]
@elshobokshy Try adding `remember` field into https://github.com/moeen-basra/laravel-react/blob/master/resources/js/modules/auth/pages/login/Page.js#L27 . Just guessing :/

**Comment by elshobokshy** [comment]
@jacekk thing is I never changed the login files, so I suppose the problem is coming from elsewhere. Any idea about the login form that is not working tho? Thanks a lot for your help!

**Comment by moeen-basra** [comment]
@elshobokshy this is the issue with update in ree-validate you can add the remember field as per the @jacekk suggestion this will work 

```
this.validator = new ReeValidate({
      email: 'required|email',
      password: 'required|min:6',
      remember: '',
    })
```

**Comment by moeen-basra** [comment]
I'm planning to upgrade this whole project but due work load not getting enough chance but I'll do this soon with a complete tutorial and documentation. Until then I'm open to help, and @jacekk I really appreciate your dedication towards the community.

**Comment by elshobokshy** [comment]
@moeen-basra just adding the value doesn't make it work, unless I'm missing something else. But that's not important, the bigger issue is that I can't properly login, did you see my first post?

**Comment by moeen-basra** [comment]
> Any idea why is the API giving me an `error: "Unauthenticated."` every time I try to login and go to the articles admin page even tho I have the admin value in the database at 1 ?

This seems to be related to your email and password you are using to login.

Please make sure you are using the right credentials.

for fresh start you can use
```
email: m.basra@live.com
pass: secret
```

**Comment by moeen-basra** [comment]
does this solve you issue ?

**Comment by elshobokshy** [comment]
It does not, I'll close the issue for now. Thanks for trying!
