### ISSUE TITLE
Some pages do not work

### ISSUE THREAD

**Issue by lfrichter** [moeen-basra/laravel-react#53]
Thanks for share the code seems well structured, anyway I found:

#### 1. No article has shown
<a href="https://imgur.com/BgQxR4d"><img src="https://i.imgur.com/BgQxR4d.png" title="source: imgur.com" /></a>

#### 2. Error when trying to add a new article
<a href="https://imgur.com/Lqmb44T"><img src="https://i.imgur.com/Lqmb44T.png" title="source: imgur.com" /></a>

**Comment by moeen-basra** [comment]
@lfrichter is it a local project or you found this issue on the live demo?

**Comment by lfrichter** [comment]
@moeen-basra I found first in my local project, and after then I checked the same on the live demo.

**Comment by moeen-basra** [comment]
@lfrichter I just check on the demo on multiple browsers it working fine.

**Comment by moeen-basra** [comment]
@lfrichter updated the repo try using the latest one
