### ISSUE TITLE
loadable component

### ISSUE THREAD

**Issue by salmansamkhan** [moeen-basra/laravel-react#59]
Hi Moeen,

I came across to your this project and it really a helpful project in learning react with laravel. 

I was wondering that instead of lazy function to load components 'React documentation says' to use this 'https://github.com/gregberge/loadable-components' library to load it from server. 

I want to know where I should change to achieve this. As I am really new to react so not able to understand how to do this.

Can you please help me out in this.

Thanks in advance brother.

**Comment by moeen-basra** [comment]
can you point me to the documentation ?

**Comment by salmansamkhan** [comment]
https://reactjs.org/docs/code-splitting.html#reactlazy

**Comment by Waqas-Sharif** [comment]
Moeen Farooq Basra,
I have cloned your project and followed all steps of first method. But when i serve the project, I could not get even view of login or register pages. Its just showing blank screen. Reply if you have any solution.

**Comment by jacekk** [comment]
@Waqas-Sharif Is it possible that #60 is causing those blank screens? Can you check DevTools > Console, whether you get the same error as described in that ticket?

cc @moeen-basra

**Comment by moeen-basra** [comment]
@Waqas-Sharif I just tried cloning a fresh, there was some issue with the validator rest are fine. Let me know if you still face some problems.
