### ISSUE TITLE
Cannot read property 'has' of undefined

### ISSUE THREAD

**Issue by jcbolor** [moeen-basra/laravel-react#60]
app.js?id=e7ffcbe9b8c258d094fc:2 TypeError: Cannot read property 'has' of undefined
    at LoginForm (9.js:1)
    at Ja (app.js?id=e7ffcbe9b8c258d094fc:2)
    at _s (app.js?id=e7ffcbe9b8c258d094fc:2)
    at lu (app.js?id=e7ffcbe9b8c258d094fc:2)
    at su (app.js?id=e7ffcbe9b8c258d094fc:2)
    at Zs (app.js?id=e7ffcbe9b8c258d094fc:2)
    at app.js?id=e7ffcbe9b8c258d094fc:2
    at t.unstable_runWithPriority (app.js?id=e7ffcbe9b8c258d094fc:2)
    at zi (app.js?id=e7ffcbe9b8c258d094fc:2)
    at Vi (app.js?id=e7ffcbe9b8c258d094fc:2)

**Comment by moeen-basra** [comment]
please report the bug in a proper format, 
OS:
Node:
npm:
and how to reproduce

**Comment by nguyenviettuananh** [comment]
> app.js?id=e7ffcbe9b8c258d094fc:2 TypeError: Cannot read property 'has' of undefined
> at LoginForm (9.js:1)
> at Ja (app.js?id=e7ffcbe9b8c258d094fc:2)
> at _s (app.js?id=e7ffcbe9b8c258d094fc:2)
> at lu (app.js?id=e7ffcbe9b8c258d094fc:2)
> at su (app.js?id=e7ffcbe9b8c258d094fc:2)
> at Zs (app.js?id=e7ffcbe9b8c258d094fc:2)
> at app.js?id=e7ffcbe9b8c258d094fc:2
> at t.unstable_runWithPriority (app.js?id=e7ffcbe9b8c258d094fc:2)
> at zi (app.js?id=e7ffcbe9b8c258d094fc:2)
> at Vi (app.js?id=e7ffcbe9b8c258d094fc:2)

yes, i've already in your situation
Btw, @moeen-basra 
My enviroment:
OS: Mac OS 10.15 Catalina
Node: 12.18
Npm: 6.14
Just clone and run `npm run dev` command, then click "Login" button on init page

<img width="1091" alt="Screen Shot 2020-09-06 at 15 41 54" src="https://user-images.githubusercontent.com/15794655/92321849-7ee55080-f057-11ea-8086-6f937965335c.png">

**Comment by moeen-basra** [comment]
I just updated the code take a pull and try again.
