### ISSUE TITLE
Someone ripped off your repo

### ISSUE THREAD

**Issue by jontas** [moeen-basra/laravel-react#63]
Was searching for a react/laravel boilerplate and I came across yours.  Then I came across this one:
https://github.com/david-whiting/Laravel-React

It is identical to yours, same code, same commits, but it is not forked.  Someone took your git history and rewrote it to make it appear that they are the author.  Seems very odd, thought I'd point it out to you, not sure if there's anything you can do it about it.

Thanks for creating this!

**Comment by jacekk** [comment]
@jontas Definitely a rip off --> https://github.com/david-whiting/Laravel-React/commit/e5ba7b8ba970c5a8f4c4ec4ccdb24f82ceced852

:facepalm: :disappointed: 

cc @moeen-basra

**Comment by moeen-basra** [comment]
lol, no worries let him help the community.

**Comment by SasSam** [comment]
@jontas Not just this project has been stolen... all of "his" projects are someone else's work...

https://github.com/david-whiting/vue-tradingview is from here: https://github.com/webdatavisualdev/vue-tradingview
https://github.com/david-whiting/Leaderboard-rails-angular is from here: https://github.com/webdatavisualdev/leaderboard-rails-angular
https://github.com/david-whiting/Shopify-Theme-Starter is from here: https://github.com/Hujjat/shopify-starter-theme

etc.

**Comment by moeen-basra** [comment]
done reported
