### ISSUE TITLE
There are no commands defined in the "cron" namespace. 

### ISSUE THREAD

**Issue by johnjoshuadablo** [moeen-basra/laravel-react#65]
Hello! Nice Repository BTW.

I followed your instruction but I'm still ending up with this error when trying this script.

`php artisan cron:refresh-database -vv`

<img width="813" alt="Screen Shot 2021-01-11 at 8 59 31 PM" src="https://user-images.githubusercontent.com/39583750/104185797-714e3600-5450-11eb-8f74-0e83ded2acb6.png">

**Comment by jinzagon** [comment]
What worked for me instead of that command:

php artisan migrate
php artisan db:seed

login : m.basra@live.com pass: i dont' really remember maybe check the db

**Comment by moeen-basra** [comment]
@jinzagon solution is currently under the hood it's doing the same thing, but I also fixed the cron.
