### ISSUE TITLE
hi i  want add React CSS Modules

### ISSUE THREAD

**Issue by msadeghifard1989** [moeen-basra/laravel-react#7]
hi 
moeen 
hi i  want add React CSS Modules 
But 
https://laracasts.com/discuss/channels/elixir/helo-using-css-modules-with-laravel-54-mix
and 
https://stackoverflow.com/questions/45792979/react-css-modules-with-laravel-mix
 Please
help me

**Comment by moeen-basra** [comment]
I will look into this in the evening.
________________________________

**Comment by msadeghifard1989** [comment]
very very  very very very very
very very very very very very very very very very very very very very very
very very very  -----------tks

**Comment by moeen-basra** [comment]
what version of laravel you are using ?

**Comment by msadeghifard1989** [comment]
how add
React CSS Modules
 guidance


From the same sample
https://github.com/moeen-basra/laravel-react

**Comment by moeen-basra** [comment]
send me user skype id on m.basra@live.com

**Comment by moeen-basra** [comment]
please follow the instructions and let me know if it works for you

install extract-text-webpack-plugin
`npm i -S extract-text-webpack-plugin`

try the following webpack config

`mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader?modules,localIdentName="[name]-[local]-[hash:base64:6]"'
                }),
            }
        ]
    },
    resolve: {
        extensions: ['.scss'],
    },
});`
