### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by cakecoke** [moeen-basra/laravel-react#70]
The stream or file "/var/www/app/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

**Comment by jacekk** [comment]
@cakecoke Please, run `ls -la /var/www/app/` and paste the output here.

It seems like one of directories is not permissioned for `www-data` user. OS version and name would be helpful. And server you are using: Apache? Nginx? Sth else?

Alternatively, try this --> https://stackoverflow.com/a/58210325

**Comment by cakecoke** [comment]
sorry for the poor reply, 
i got  Docker version 20.10.6, build 370c289
on Ubuntu 20.04
trying to run it in container

**Comment by moeen-basra** [comment]
this issue is not with the app its a problem with the permission of the storage folder.

You can try this 

```bash
sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache
```
