### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by grnarayan** [moeen-basra/laravel-react#72]
Following the READ.md (option 2), Docker option.
On step 2 
`php artisan cron:refresh-database`

 I am getting 

`"SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = laravel_react and table_name = migrations and table_type = 'BASE TABLE')" message
`

**Comment by moeen-basra** [comment]
make sure you are inside the docker container to run this otherwise check your local database configuration
