### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by 4emp1ON** [moeen-basra/laravel-react#73]
Error during migrations apply. 
Migration not found: 2016_06_01_000005_create_oauth_personal_access_clients_table
Migration not found: 2016_06_01_000004_create_oauth_clients_table
Migration not found: 2016_06_01_000003_create_oauth_refresh_tokens_table
Migration not found: 2016_06_01_000002_create_oauth_access_tokens_table
Migration not found: 2016_06_01_000001_create_oauth_auth_codes_table

As a result can't login.

**Comment by moeen-basra** [comment]
pull and rebuild the docker container and try again
